### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by KolyaBlacK** [BayBreezy/nuxt-tour#148] opened 2024-12-17 16:02 UTC
Hi,

I'm encountering a TypeScript error when using your library. Could you fix it or help me resolve it?

`ERROR(vue-tsc)  Could not find a declaration file for module 'lodash/merge'. '/PATH/node_modules/lodash/merge.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/lodash if it exists or add a new declaration (.d.ts) file containing declare module 'lodash/merge';
 FILE  /PATH/node_modules/nuxt-tour/dist/runtime/components/Tour.vue:274:21`
 
 P.S. Installing @types/lodash as a direct dependency in the final project doesn't seem like the most elegant solution.

<img width="1533" alt="Screenshot 2024-12-17 at 18 59 49" src="https://github.com/user-attachments/assets/85f658b7-24e0-4add-95cc-c45af7b45ecd" />

**Comment by BayBreezy** [comment] 2024-12-18 03:52
@KolyaBlacK It should be fixed in latest release.
Can you check and let me know please? Thanks

**Comment by KolyaBlacK** [comment] 2024-12-18 06:17
Hi @BayBreezy, thanks for the fix! Everything is working now without any TypeScript errors!

**Comment by BayBreezy** [comment] 2024-12-18 15:08
Awesome! Thanks again for bringing this up.

**Comment by EvanSchleret** [comment] 2024-12-19 10:15
Hi,

I created a new blank Nuxt app and installed only your module. However, even with your latest release, I’m encountering the same issue. Additionally, when I install the module, I can’t find the @types/lodash package in my node_modules folder, even though I see it listed as a dependency in your package.json.

Initially, I tried installing the module using pnpm, which is the package manager I use daily, but it didn’t work. So, I created another blank project using npm and installed only your module. This time, something different happened.

![image](https://github.com/user-attachments/assets/9ed20e64-284f-450b-a24d-958346740f03)

This might be a silly question since I don’t think it should matter, but… Is your module compatible with the pnpm package manager?

Do you know why I’m still encountering this error, even with npm?

The blank project I created only includes your module and the default Nuxt base modules.

**Comment by EvanSchleret** [comment] 2024-12-22 15:12
I created a repo where I reproduced a very small installation of a Nuxt app with your module. Hope you'll find something I didn't see ;)

https://github.com/EvanSchleret/vtour-test

**Comment by BayBreezy** [comment] 2024-12-22 17:03
Ty. I will check it out.

**Comment by BayBreezy** [comment] 2024-12-22 17:20
@EvanSchleret the issue was fixed with that release just now. Test it out and let me know plz.

I don't use pnpm so that is why i did not catch it earlier. Thanks for the reproduction. It helped a lot

**Closed by BayBreezy** 2024-12-22 17:20 UTC

**Comment by EvanSchleret** [comment] 2024-12-22 18:36
It's solved, thank you :)
