### ISSUE TITLE
[worker reload] [worker init] Package subpath './runtime' is not defined by "exports"

### ISSUE THREAD

**Issue by geofany** [BayBreezy/nuxt-tour#48] opened 2024-08-06 11:55 UTC
<img width="998" alt="Screenshot 2024-08-06 at 18 54 58" src="https://github.com/user-attachments/assets/3ecb672b-9076-4b36-863f-41d9ca8af149">

Nuxt 3.8.2
Node 20.12.2

**Comment by BayBreezy** [comment] 2024-08-06 13:47
Hey. Are you able to update the nuxt version and see if it's the same thing?

**Comment by BayBreezy** [comment] 2024-08-18 23:02
Hey @geofany , I am closing this one as I am not able to reproduce it with a newer version of nuxt

**Closed by BayBreezy** 2024-08-18 23:02 UTC
